# Generated by Django 5.2.8 on 2025-12-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='voluntarios',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='voluntarios.voluntario'),
        ),
    ]
